Upgrade "temp" module to 0.9.4
The older version of "temp" does not work under Node 14, with "TypeError: os.tmpDir is not a function". `os.tmpDir` has long been deprecated in favor of `os.tmpdir`, which has been available since at least Node 0.10.x, and Node 14 has finally removed the deprecated function.